apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"   
        prometheus.io/port: "80"       
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: user-service
        image: containerdemo112.azurecr.io/user-service:latest
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: acr-auth