apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3003"
spec:
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3003
  type: LoadBalancer
