name: CI/CD Pipeline for Microservices

on:
  push:
    branches:
      - master  

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker images
      - name: Build and push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/user:latest

      - name: Build and push Product Service
        uses: docker/build-push-action@v4
        with:
          context: ./product-service
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/product:latest

      - name: Build and push Order Service
        uses: docker/build-push-action@v4
        with:
          context: ./order-service
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/order:latest

      # Deploy to AKS
      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}
          kubectl apply -f user-service/deployment.yaml
          kubectl apply -f user-service/service.yaml
          kubectl apply -f product-service/deployment.yaml
          kubectl apply -f product-service/service.yaml
          kubectl apply -f order-service/deployment.yaml
          kubectl apply -f order-service/service.yaml